import type { Metadata } from "next";
import { Oxanium, Mulish } from "next/font/google";
import "./globals.css";

const oxanium = Oxanium({ subsets: ["latin"], variable: "--font-heading" });
const mulish = Mulish({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${oxanium.variable} ${mulish.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
